services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py index_documents --clear && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8000/api/health/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
