[tool.isort]
profile = "black"
line_length = 127
skip_gitignore = true
skip = [".venv", "venv", "env", "migrations"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
line-length = 127
target-version = ['py310', 'py311', 'py312']
extend-exclude = '''
/(
    \.venv
  | venv
  | migrations
)/
'''
