# Generated by Django 5.1 on 2025-10-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('text', models.TextField()),
                ('embedding', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['doc_id'],
                'indexes': [models.Index(fields=['doc_id'], name='search_api__doc_id_5c9a01_idx')],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('query_text', models.TextField()),
            ],
            options={
                'ordering': ['query_id'],
                'indexes': [models.Index(fields=['query_id'], name='search_api__query_i_ef79a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, max_length=100)),
                ('doc_id', models.CharField(db_index=True, max_length=100)),
                ('relevance_score', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['query_id'], name='search_api__query_i_af913b_idx'), models.Index(fields=['doc_id'], name='search_api__doc_id_337050_idx')],
                'unique_together': {('query_id', 'doc_id')},
            },
        ),
    ]
